on:
  push:
    branches:
      - $default-branch
  pull_request:
  workflow_dispatch:
name: Linkinator CI
jobs:
  linkinator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: "**/*.md"
          markdown: true
          retry: true
          verbosity: 'ERROR'
          linksToSkip: >-
             # Not sure why these fail
             https://developer.android.com/docs,
             https://docs.riak.com/, 
             https://www.linode.com/docs/, 
             https://pretty-rfc.herokuapp.com/
